- name: Start sandbox instances
  hosts: localhost
  gather_facts: false
  vars:
    type:
      - Installer
      - worker
      - master
    region: us-east-2
  vars_files:
    - /home/ec2-user/playbooks/keys.yaml
  tasks:
    - name: Start the sandbox instances
      ec2:
        ec2_access_key: "{{ec2_access_key}}"
        ec2_secret_key: "{{ec2_secret_key}}"
        instance_tags:
          ocp: "{{ type }}"
        region: "{{ region }}"
        state: 'running'
